// js/components/Education.jsx
import React from 'react';
import {
  Item,
  ItemContent,
  ItemDescription,
  ItemGroup,
  ItemHeader,
  ItemImage
} from 'semantic-ui-react';

const Education = ({ educationList, images }) => {
  var items = educationList.map((education, i) => {
    var details = education.details.map((detail, j) => (
      <div key={`education${i}detail${j}`}>{detail}</div>
    ));
    return (
      <Item key={`education${i}`}>
        <ItemImage size="tiny" src={images[education.image_name]} />
        <ItemContent verticalAlign="middle">
          <ItemHeader content={education.school} />
          <ItemDescription content={details} />
        </ItemContent>
      </Item>
    );
  });
  return <ItemGroup relaxed content={items} />;
};

export default Education;

// js/components/Education.svelte
<script>
export let educations;
export let images;
</script>

<section>
  <h2 class="ui header">
    <i class="graduation cap icon"></i>
    <div class="content">Education</div>
  </h2>
  <div class="ui relaxed items">
    {#each educations as education}
      <div class="item">
        <div class="ui tiny image">
          <img src="{images[education.image_name]}" alt="">
        </div>
        <div class="middle aligned content">
          <div class="header">
            {education.school}
          </div>
          <div class="description">
            {#each education.details as detail}
              <div>{ detail }</div>
            {/each}
          </div>
        </div>
      </div>
    {/each}
  </div>
</section>
