// js/components/education.vue
<template lang="pug">
section
  h2.ui.header
    i.graduation.cap.icon
    .content Education
  .ui.relaxed.items
    .item(v-for="education in educations")
      .ui.tiny.image
        img(v-bind:src="images[education.image_name]")
      .middle.aligned.content
        .header {{ education.school }}
        .description
          div(v-for="detail in education.details")
            | {{ detail }}
</template>

<script>
export default {
  props: {
    educations: Array,
    images: Object
  }
}
</script>

<style></style>

// js/components/Education.svelte
<script>
export let educations;
export let images;
</script>

<section>
  <h2 class="ui header">
    <i class="graduation cap icon"></i>
    <div class="content">Education</div>
  </h2>
  <div class="ui relaxed items">
    {#each educations as education}
      <div class="item">
        <div class="ui tiny image">
          <img src="{images[education.image_name]}" alt="">
        </div>
        <div class="middle aligned content">
          <div class="header">
            {education.school}
          </div>
          <div class="description">
            {#each education.details as detail}
              <div>{ detail }</div>
            {/each}
          </div>
        </div>
      </div>
    {/each}
  </div>
</section>
