// js/components/ItemDetails.svelte
<script>
  export let details;
</script>

<style>
  .content > .list {
    padding: 0em !important;
  }
</style>

<div class="ui relaxed list">
  {#each details as detail}
    <div class="ui item">
      {#if Array.isArray(detail)}
        <div class="content">
          <div class="list">
            {#each detail as sub_detail}
              <div class="item">
                <i class="triangle right icon"></i>
                <div class="content">{sub_detail}</div>
              </div>
            {/each}
          </div>
        </div>
      {:else}
        <div class="content">{detail}</div>
      {/if}
    </div>
  {/each}
</div>

// js/components/ItemDetails.jsx
import React from 'react';
import { List, ListItem } from 'semantic-ui-react';

const ItemDetails = ({ details, keyPrefix }) => {
  var listContent = details.map((detail, i) => {
    if (typeof detail === 'object') {
      var subListContent = detail.sub_details.map((sub_detail, j) => (
        <ListItem
          icon="triangle right"
          key={`${keyPrefix}detail${i}subdetail${j}`}
          content={sub_detail}
        />
      ));
      return (
        <ListItem key={`${keyPrefix}detail${i}`}>
          {detail.data}
          <List content={subListContent} />
        </ListItem>
      );
    } else {
      return <ListItem key={`${keyPrefix}detail${i}`} content={detail} />;
    }
  });
  return <List relaxed content={listContent} />;
};

export default ItemDetails;
