// js/components/Layout.jsx
import React from 'react';
import {
  Container,
  Grid,
  GridColumn,
  GridRow,
  Header,
  Image
} from 'semantic-ui-react';
import Images from '../../img/*.jpg';
import Objective from '../components/Objective';
import Title from '../components/Title';
import resumeData from '../data/resumeData';
import Education from './Education';
import Experience from './Experience';
import Links from './Links';
import Projects from './Projects';

const Layout = () => (
  <Container className="page-container">
    <Grid stackable columns={2}>
      <GridRow divided>
        <GridColumn width={11}>
          <Title name={resumeData.name} />
          <Objective objective={resumeData.objective} />
        </GridColumn>
        <GridColumn width={5}>
          <Image rounded src={Images['profile-img']} size="tiny" />
          <Links linkList={resumeData.links} />
        </GridColumn>
      </GridRow>
    </Grid>

    <Header as="h2" icon="briefcase" content="Experience" />
    <Experience experienceList={resumeData.experience_list} images={Images} />

    <Header as="h2" icon="code" content="Projects" />
    <Projects projects={resumeData.project_list} images={Images} />

    <Header as="h2" icon="graduation cap" content="Education" />
    <Education educationList={resumeData.education_list} images={Images} />
  </Container>
);

export default Layout;

// js/components/layout.vue
<template lang="pug">
.ui.container.page-container
  .ui.stackable.two.column.grid
    .divided.row
      .eleven.wide.column
        page-title(v-bind:name="resume.name")
        objective(v-bind:objective="resume.objective")
      .five.wide.column
        img.ui.tiny.rounded.image(v-bind:src="images['profile-img']")
        links(v-bind:links="resume.links")
  experience(
    v-bind:experiences="resume.experience_list"
    v-bind:images="images"
  )
  projects(
    v-bind:projects="resume.project_list"
    v-bind:images="images"
  )
  education(
    v-bind:educations="resume.education_list"
    v-bind:images="images"
  )
</template>

<script>
import PageTitle from './page-title.vue';
import Images from '../../img/*.jpg';
import Links from './links.vue';
import Experience from './experience.vue';
import Objective from './objective.vue';
import Projects from './projects.vue';
import Education from './education.vue';

export default {
  data: () => ({
    images: Images
  }),
  props: {
    resume: Object,
  },
  components: {
    PageTitle,
    Links,
    Experience,
    Objective,
    Projects,
    Education
  }
}
</script>

<style>
.page-container {
  margin-top: 3rem;
  margin-bottom: 3rem;
}
</style>
