// js/components/projects.vue
<template lang='pug'>
section
  h2.ui.header
    i.code.icon
    .content Projects
  .ui.relaxed.items
    .item(v-for='project in projects')
      .ui.small.image
        img(v-bind:src="images[project.image_name]")
      .content
        .header {{ project.name }}
        .extra
          .ui.label
            i.calendar.icon
            | {{ project.time_range }}
          a.ui.red.label(
            v-if="project.video_id"
            v-bind:href="'https://www.youtube.com/watch?v=' + project.video_id"
          )
            i.icon(v-bind:class="project.video_source")
            | Watch Video
        .description
          item-details(v-bind:details="project.details")
</template>

<script>
import ItemDetails from './item-details.vue'

export default {
  props: {
    projects: Array,
    images: Object
  },
  components: {
    ItemDetails
  }
}
</script>

<style></style>

// js/components/Projects.svelte
<script>
  import ItemDetails from './ItemDetails.svelte';

  export let projects;
  export let images;
</script>

<section>
  <h2 class="ui header">
    <i class="code icon"></i>
    <div class="content">Projects</div>
  </h2>
  <div class="ui relaxed items">
    {#each projects as project}
      <div class="item">
        <div class="ui small image">
          <img src="{images[project.image_name]}" alt="">
        </div>
        <div class="content">
          <div class="header">{project.name}</div>
          <div class="extra">
            {#if project.time_range}
              <div class="ui label">
                <i class="calendar icon"></i>
                {project.time_range}
              </div>
            {/if}
            {#if project.video_id}
              <a class="ui red label" href="https://www.youtube.com/watch?v={project.video_id}">
                <i class="map {project.video_source} icon"></i>
                Watch Video
              </a>
            {/if}
          </div>
          <div class="description">
            <ItemDetails details="{project.details}" />
          </div>
        </div>
      </div>
    {/each}
  </div>
</section>
